### ISSUE TITLE
Hashbang python sequence in ttx script

### ISSUE THREAD

**Issue by MrBrezina** [behdad/fonttools#272]
The ttx shell script currently looks like this:

```
#!/usr/bin/python

import sys
from fontTools import ttx

ttx.main(sys.argv[1:])
```

Would not this be more practical? I mean, in an environment where I do not even remeber how many Python versions I have installed (pre-installed with the system, installed with homebrew etc.).

```
#!/usr/bin/env python

import sys
from fontTools import ttx

ttx.main(sys.argv[1:])
```

**Comment by anthrotype** [comment]
Yeah, that could be changed like you say (why don't you send a PR?).

The thing is, when the user runs "python setup.py install", distutils will automatically set the shebang of the installed scripts to match the python interpreter used to execute the setup.py script.

I just tried installing fonttools in a new virtual environment, and here is the shebang of the installed scripts (including ttx), after running setup.py:

    #!/Users/cosimolupo/Documents/venv/fonttools_distutils_test/bin/python

**Comment by MrBrezina** [comment]
Hmm. it did not happen for me for some reason. Will do the PR.

**Comment by anthrotype** [comment]
it's not the original scripts in the source folder that get modified by distutils, but the ones that goes into your /usr/local/bin (or equivalent) folder, after running the install command.

**Comment by MrBrezina** [comment]
Oh wait! The code is already like that. I did not know the distutils modify it. So, it is a problem on my side. This closes it then. :)

**Comment by anthrotype** [comment]
By the way, if you don't want to install a new copy of fonttools in your site-packages, but instead wish to run directly from the source folder, you can install in "development" mode.

There is a "develop" command available in setuptools -- though unfortunately not in the built-in distutils --, which creates a symbolic link to the package's source folder in you python's site-packages, and also creates "wrappers" for each script, pointing to the respective source files, with a modified shebang referring to the specified python interpreter.

Because fonttools's setup.py script only uses distutils, you can enable the setuptools' "develop" command by simply pre-pending "import setuptools" to the setup.py script, like that:

    python -c "import setuptools; exec(open('setup.py').read())" develop

**Comment by MrBrezina** [comment]
Neat!

**Comment by behdad** [comment]
Cosimo, feel like submitting a PR to port to setuptools?

**Comment by anthrotype** [comment]
I'm all for a more up-to-date setup process. Even the Python Packaging Authority now recommends setuptools as the default choice for packaging source distributions:

https://python-packaging-user-guide.readthedocs.org/en/latest/current.html

In the latest installers from python.org, starting from Python 2.7.9, 3.4 and later, the user can choose to install pip, and so have setuptools installed as part of the pip requirements.

However, we should bear in mind that, unlike distutils, setuptools is not part of the standard library yet.
Currently FontTools can be installed on any Python 2.6 and later, without requiring any external dependencies.

So do we want to have setuptools as a dependency for FontTools?

If it's just for the sake of enabling the "develop" command or running "bdist_wheel", then one could do the above mentioned trick -- which, by the way, is the same thing that pip performs when building a distutils package from source.

**Comment by anthrotype** [comment]
@djdm just reminded me one can also use pip to run the setuptools "develop" command:

    pip install -e .

This will install a package in "editable" mode (same as setuptools "develop" mode).
The working directory is the root of the package, where setup.py is located.

**Comment by anthrotype** [comment]
I sent a PR for the setup.py that enables setuptools. The distutils method still works, if setuptools is not installed.

One major advantage of setuptools over distutils is the ability to automatically create platform-specific command line scripts, via the "console_scripts" entry point. For example, on Windows, it will create *.exe files which wraps the python scripts, so that users don't have to use any py2exe, nor have to add ".py" to their PATHEXT variable.
