### ISSUE TITLE
[BUG] `ttx -z extfile -o outfile.ttx` writes the `bitmap` folder in the wrong location

### ISSUE THREAD

**Issue by twardoch** [behdad/fonttools#295]
Let's say I do 
```
mkdir out
ttx -t CBDT -t CBLC -z extfile -o out/myfont.ttx myfont.ttf
```
or
```
mkdir out
ttx -t CBDT -t CBLC -z extfile -d out myfont.ttf
```
then I expect that ttx will create the `bitmap` subfolder in the `out` subfolder, i.e. in the location specified by `-o <outfile>` or `-d <outdir>`. But ttx always creates the `bitmap` subfolder in the current working directory. However, the `out/myfont.ttx` file will make references to `<extfileimagedata value="bitmaps/strike0/glyph2784.png"/>` so it expects the location `out/bitmaps/strike0/glyph2784.png`. 

So at this point, I have to manually move `bitmap` to `out`, or otherwise, merging won't work.

**Comment by anthrotype** [comment]
The problem seems to be in function `_writeExtFileImageData` of module E_B_D_T:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/E_B_D_T_.py#L341
The location of the `bitmaps/` folder is always set to the current working directory, whereas it should be possible to set a different one based on the location of the output ttx file.
One solution could be to get the path to the output TTX file from the `writer` object which is passed along as an argument; `writer` has a `file` attribute, which in turn should have a `name` attribute for the filename. I'll try that and see if this solves it.

**Comment by anthrotype** [comment]
@twardoch could you try and see if #297 fixes the issue?
thank you.
