### ISSUE TITLE
Windows 7 fails to load AmaticSC after roundtripping with TTX

### ISSUE THREAD

**Issue by Ziriax** [behdad/fonttools#335]
When dumping the AmaticSC-Regular font to TTX, and then reconstructing the TTF using TTX again, the resulting font does not open correctly on Windows 7, the text is displayed using an arial-like fallback font.

The command line was just

```
TTX AmaticSC-Regular.ttf
TTX AmaticSC-Regular.ttx
```

Re-generating the font using FontForge does work

**Comment by Ziriax** [comment]
Sorry, I forgot to mention that I'm using the [AmaticSC-Regular](https://github.com/google/fonts/blob/master/ofl/amaticsc/AmaticSC-Regular.ttf) from the Google Fonts repository

**Comment by anthrotype** [comment]
Hi @Ziriax, thanks for reporting this.
I seems like the GPOS table might be the problem. If you remove it from the TTX and try to compile it, you'll see the font is loaded by Windows.
The GPOS in the original font seems to contain no features nor lookups, but only two script records (`DFLT dflt` and `latn dflt`) pointing nowhere.
We need to investigate further the reason why Windows fails to load the fontTools-recompiled GPOS table, but doesn't complain about the original one.

**Comment by Ziriax** [comment]
Thanks for the very fast feedback, you guys are amazing

**Comment by anthrotype** [comment]
Interestingly, I just tried to loading the roundtripped font in Windows 8.1 and it works... hmm

**Comment by Ziriax** [comment]
It might be that the font preview panel in Windows 7 is still using GDI.

I tested the font with our DirectWrite-based renderer on Windows 7, and it renders fine. 

Since I believe Chrome, Firefox and IE now all use DirectWrite on Windows, this issue might not be that problematic, and might just be a bug in GDI?

**Comment by anthrotype** [comment]
True. The roundtripped font works in the latest browsers, as well as in Word 2013. These all use DirectWrite. It fails to load in Windows Preview and in Notepad, for example.
Still, I want to understand why FontForge's GPOS table is not rejected by Windows GDI, but fontTools' is.

**Comment by Ziriax** [comment]
As a sidenote, I also reported [here](https://github.com/google/fonts/issues/95) that the AmaticSC-Regular font (version 1.003) as currently stored in the Google Fonts repository is also problematic, while the 1.001 version of the font does work. Maybe that can help.

**Comment by anthrotype** [comment]
I'm not sure fontTools should take care of this... It seems like a Windows 7 bug which affects only GDI rendering. Other OSes (including later Windows versions) don't complain about it. Similarly the OpenType Sanitiser doesn't say anything about GPOS (it only complains about the gasp table version which is set to 0 in the original font, but that's not it). Even Microsoft FontValidator seems happy about the GPOS.

Anyway, I inspected the two GPOS tables, as generated by FontForge and fontTools/TTX, using a hex editor. The size of the latter shrinks from 48 to 36 bytes, because fontTools point the two ScriptRecords to the same `ScriptTable` and (empty) `FeatureList` and `LookupList` structs, instead of repeating them twice like FontForge does. This is perfectly legal by the OT spec, so I can't see why Windows 7 (GDI) would refuse to load the whole font just because of that...

**Comment by Ziriax** [comment]
Microsoft has an old tool called [Font Validator](http://www.microsoft.com/typography/FontValidator.mspx).

Not sure if this can help.

If I run the tool on version 1.001 and 1.003 of the font, I get many warnings and errors for both of them, but I get more errors for 1.003, namely:

```
gasp
E1003 The version number is not 0 

loca
E1703 Loca entry points outside the glyf range Number of glyphs with the error = 1 
W1701 Loca references a glyf entry which length is not a multiple of 4 Number of glyphs with the warning = 110 

name
E2003 The table doesn't contain strings for Mac platform  
E2008 The PostScript string is not present for both required platforms Mac Postscript string is missing, but MS Postscript string is present 
```

**Comment by anthrotype** [comment]
Yes, I did mention FontValidator in my previous message.
The reason the font isn't being loaded has nothing to do with either gasp, loca or name tables.
It is specifically the GPOS table, as recompiled by fontTools, which Windows 7 GDI doesn't seem to like. All the other warnings/errors you see in FontVal report do not prevent the font from being loaded by Windows.
I managed to isolate the problem by re-compiling selectively each single table until I found that the GPOS was the issue.

**Comment by anthrotype** [comment]
Let me stress this point again: the GPOS table as recompiled by fonttools is perfectly fine. It is Windows 7 which fails to load it because of some bug that appears to be fixed now.
If you want the font to render in Windows 7 GDI, even after passing it thorugh TTX, you can simply get rid of that stub GPOS table which serves no purposes, since it has no features/lookups.

**Comment by Ziriax** [comment]
Sorry, my bad! I just found the LOCA error very suspicious, and thought it might be useful info.

**Comment by anthrotype** [comment]
The FontVal error message about loca table "pointing outside of the glyf range" is related to the fact that the last glyph in Amatic SC 1.003 font is an empty glyph, without any contours nor components: namely "nbsp" (GID 380). If you replace it with another non-empty glyph, the message should disappear.

**Comment by behdad** [comment]
Still would be interesting to understand what in particular is causing this.
