### ISSUE TITLE
pyftsubset: Can't keep 'SVG ' table

### ISSUE THREAD

**Issue by RoelN** [behdad/fonttools#376]
If I add `--drop-tables-='SVG '` like shown in the docs, the 'SVG ' table is still dropped:

`pyftsubset --verbose --drop-tables-='SVG ' compyx.ttf '*'`

```
SVG  dropped

**Comment by anthrotype** [comment]
@RoelN thanks for reporting this.
Space characters in strings passed to pyftsubset are being stripped out by its argument parser.
I just sent a patch to fix the issue: https://github.com/behdad/fonttools/pull/377
Could you please have a look?

Also, note that because the subsetter does not know how to subset the "SVG " table, even if you tell it to not `--drop-tables-='SVG '`, that table will be dropped anyway. In order to keep it, you will need to pass `--no-subset-tables+='SVG '` option, in addition to `--drop-tables-='SVG '`.

I hope this makes sense.

**Comment by RoelN** [comment]
@anthrotype Sorry, wasn't able to check earlier. This works now, and having to tell you don't want to subset the 'SVG ' table does make sense. (The feedback is good too: "SVG  NOT subset; don't know how to subset; dropped")

Thanks for fixing this!
