### ISSUE TITLE
cmap format 14 compile fails if attributes missing

### ISSUE THREAD

**Issue by dougfelt** [behdad/fonttools#389]
Creating a format 14 cmap programatically fails if some expected attribute is missing.  This is probably true of some other formats as well.

When table__c_m_a_p.compile is called, it compiles all of the cmaps in its tables attribute.  After each table, it writes the table's platformID and platEncID as well as the offset into the index part of the data.

Accessing attributes of the table triggers the __getattr__ method of CmapSubtable (which the various formats subclass) on access to a missing attribute.  In the case of format 14, platformID is always 0 and platEncID is always 5, so it seems reasonable to omit these when manually constructing the cmap.  __getattr__ calls decompile with None for data and font. The intent of this is (apparently) to build the required attributes by calling decompile using the cmap's local copy of its just-compiled data, after which all required attributes should be set (so the local data is discarded).  

However, decompile from the cmap's data fails because decompiling from local data (in format 14 and elsewhere) bypasses decompileHeader when called with no data or ttFont argument.  This bypasses the code in decompileHeader that processes and skips past the header portion of the data, and leaves decompile with data starting at the header instead of past it.  When decompile tries to process what it thinks is post-header data, it fails.

The fix is to ensure the header data is always processed (except perhaps for setting ttFont) regardless of how decompile is entered.  I think this is better than simply chopping off the lead of the data since (in format 14 at least) decompileHeader sets attributes such as language that reasonably could be omitted when initializing the cmap manually (since language always has the same value).

**Comment by fred-wang** [comment]
I found a similar issue when trying to use fonttools for my https://github.com/fred-wang/MathFonts/ repository. I'm not sure whether it's exactly the same problem, but here are the steps to reproduce the error:

1) Download XITS 1.108 at https://github.com/khaledhosny/xits-math/releases/tag/v1.108
2) Extract xits-math.otf
3) Execute the following script to compile and decompile the cmap table:

```
from fontTools.misc.py23 import *
from fontTools.ttLib import TTFont
from xmlWriter import XMLWriter

font = TTFont("xits-math.otf")
font["cmap"].compile(font)
font.save("xits-math-2.otf")

font2 = TTFont("xits-math-2.otf")
writer = XMLWriter(BytesIO())
font2["cmap"].toXML(writer, font2)

```

4) fonttool fails with the following backtrace:
```
Traceback (most recent call last):
  File "test-xits-math.py", line 11, in <module>
    font2["cmap"].toXML(writer, font2)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 102, in toXML
    table.toXML(writer, ttFont)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 1166, in toXML
    uvsDict = self.uvsDict
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 144, in __getattr__
    self.decompile(None, None) # use saved data.
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/_c_m_a_p.py", line 1124, in decompile
    numValues, = struct.unpack(">L", data[startOffset:startOffset+4])
struct.error: unpack requires a string argument of length 4

```

**Comment by anthrotype** [comment]
Thanks both @dougfelt and @fred-wang for the bug report.
I believe I've found a solution for this bug. The fix is much shorter than the following discussion, but I feel like I need to explain this a little bit as it's quite confusing.

First, unlike the other subtable classes, the `cmap_format_14.compile` method stores the compiled data in the attribute `self.data = headerdata + data` ([line 1268](https://github.com/behdad/fonttools/blob/ff853c38b886d7c1c814b982d782efa109bc8663/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L1268)). For all other subtables classes, the `compile` method simply checks at the beginning if a `self.data` attribute is present, and if so it reuses that; otherwise it simply recompiles the cmap subtable, without storing the result at the end.

In the snippet by @fred-wang above, when the statement `font["cmap"].compile(font)` is run, all cmap subtables get decompiled and recompiled, including the format 14 subtable -- which will now have a `self.data` attribute, containing _both_ the subtable header and the data that follows the header.

Then, when `font.save("xits-math-2.otf")` gets called, all sfnt tables, including "cmap", are recompiled; when it's the turn of the `cmap_format_14` subtable, because it already has a `self.data` attribute (having been manually recompiled in the line before), its `compile` method will attempt to reuse `self.data`; _but_ it will add _again_ the header data to it, so that now it will contain it twice! ([lines 1208-1209](https://github.com/behdad/fonttools/blob/ff853c38b886d7c1c814b982d782efa109bc8663/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L1208-L1209)):

```python
if self.data:
    return struct.pack(">HLL", self.format, self.length, self.numVarSelectorRecords) + self.data
```

Of course, once the `decompile` method of `cmap_format_14` is called on such corrupt data (in @fred-wang example, when he tries to dump the cmap table to XML), the decompilation will fail. That's because, when a subtable `decompile` method is called with `data` and `ttFont` arguments set to `None`, it is assumed that `self.data` will only contain "the data after the header to self.data" (this is repeated several times in the inline comments); in fact, in all subtable classes, `self.data` gets only assigned by the `decompileHeader` method, and is consumed by the respective `decompile` method as soon as a missing attribute is accessed. It's only in the format 14 one that there's an exception to the rule: i.e. `self.data` gets assigned again inside `compile` -- but in a wrong way, as `headerdata + data`, instead of `data` only.

The fix then is simple: don't set `self.data` inside `cmap_format_14.compile`, just like we don't in the other subtable classes. Then, even if the user calls the cmap `compile` method directly (with the intention of decompiling and force-recompile all subtables, as in @fred-wang example), the `cmap_format_14` will not try to reuse `self.data` the next time it's compiled (i.e. by the `TTFont.save` method), but will recompile itself from the decompiled data.

Another solution would have been to set `self.data` attribute to simply `data` instead of the current `headerdata + data`. However, none of the other subtable classes do this in their `compile` methods, so I don't see why `cmap_formata_14` should be an exception.

This is the patch I'm going to commit.
I'm confident this will solve @fred-wang issue, but I'm not sure it also solves @dougfelt's.
Please confirm that is the case when you have some spare time.

Cheers!

```diff
diff --git a/Lib/fontTools/ttLib/tables/_c_m_a_p.py b/Lib/fontTools/ttLib/tables/_c_m_a_p.py
index 141a0d4..b9447ff 100644
--- a/Lib/fontTools/ttLib/tables/_c_m_a_p.py
+++ b/Lib/fontTools/ttLib/tables/_c_m_a_p.py
@@ -1265,9 +1265,8 @@ class cmap_format_14(CmapSubtable):
 		data = bytesjoin(varSelectorRecords) + bytesjoin(data)
 		self.length = 10 + len(data)
 		headerdata = struct.pack(">HLL", self.format, self.length, self.numVarSelectorRecords)
-		self.data = headerdata + data
 
-		return self.data
+		return headerdata + data
 
 
 class cmap_format_unknown(CmapSubtable):
```
