### ISSUE TITLE
[feaLib] allow string as input

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#443]
feaLib should have an entry-point that takes a string of features as input and works with that.

See jamesgk/ufo2ft#9. cc @brawer

**Comment by adrientetar** [comment]
@brawer, any plans to support this?

**Comment by brawer** [comment]
Sure, of course! Mind sending a pull request?

**Comment by anthrotype** [comment]
In the TTFont's constructor, as well as in the xml readers and writers, we allow the user to pass in either a file path or an already open file-like object (with a "name" string attribute containing its filesystem path, if any).

Here however, we opted for two arguments (at least one of which is required), one containing the path to the feature file, and the other the string data.

Wouldn't it better and more consistent to also use the `fileOrPath` approach for feaLib? That is, `addOpenTypeFeatures` (and consequently, the Builder, Parser and Lexer classes) would take in a single argument which can be either a string (and hence it's understood as a path) or it may have `read` method and thus be interpreted as an open file or stream?

If one wants to pass in a string instead of opening a file from a path, one would wrap that string in a StringIO and pass that to the `addOpenTypeFeatures`.

WDYT?

**Comment by brawer** [comment]
Sounds reasonable. Send a pull request?

**Comment by anthrotype** [comment]
Ok, I'll do that.

**Comment by justvanrossum** [comment]
I'd prefer two distinct functions, say addOpenTypeFeaturesFromString() and addOpenTypeFeaturesFromFile(). If I have data as a string, I always feel a little betrayed if I have to wrap it into a StringIO object. Especially if I know it will later read all the data into memory anyway.

**Comment by anthrotype** [comment]
hm, I see what you mean.
but would `addOpenTypeFeaturesFromFile` take a filename (string) or a file (object) or either?

**Comment by justvanrossum** [comment]
I don't think a file object will be a common use case here, will it?

But it's getting a little messy in the context of include(). So perhaps the current situation is as good as it gets: it takes a filename *and* data and if data is given, the filename will be used for resolving the include() location.

**Comment by anthrotype** [comment]
yeah, perhaps.. It just felt a bit strange having to pass around two arguments (or one tuple argument), where a single file object (containing both the string data and the filename) would seem appropriate.
But I don't really mind leaving it as it is.

**Comment by khaledhosny** [comment]
I prefer @anthrotype’s approach for the reasons he mentioned, as well as for consistency with the existing API. A filename is needed any way for resolving relative includes so we will always have to pass one. Wrapping everything in a file like object would be better than having to pass two arguments all over the place.

**Comment by adrientetar** [comment]
> A filename is needed any way for resolving relative includes so we will always have to pass one.

Not necessarily, if you know the code has no relative includes (e.g, output from a code writer).

> I'd prefer two distinct functions, say addOpenTypeFeaturesFromString() and addOpenTypeFeaturesFromFile().

I personally like the current func because you may have path or data or both.

**Comment by anthrotype** [comment]
If the filename is missing, we could give the feature file an arbitrary name `<featurefile>` (for printing `filename:line:column` error messages), and all relative includes could be interpreted as relative to the current working directory as returned by `os.getcwd()`.

I'm working on a patch so we can discuss this on a real example.

**Comment by khaledhosny** [comment]
> If the filename is missing, we could give the feature file an arbitrary name <featurefile> (for printing filename:line:column error messages), and all relative includes could be interpreted as relative to the current working directory as returned by os.getcwd().

That is basically what I did when I added such a feature to (my fork of) FontForge, so I agree completely.

**Comment by anthrotype** [comment]
ah so SortsMill now uses feaLib? :+1:

**Comment by khaledhosny** [comment]
On, no not feaLib, but I while ago I added a method to apply font feature from string to the existing C code (and incidentally I hacked it by using FILE-like objects in C as well). Now I’m trying to use feaLib exclusively, enough hacking C-based type tools for one life.

**Comment by anthrotype** [comment]
I have a sent a PR with the proposed change: https://github.com/behdad/fonttools/pull/556

The `addOpenTypeFeatures` function, the `Builder` and `Parser` classes, and the Lexer's `make_lexer_ ` static method can take one `featurefile` argument which can be either a path or a file object.

I also added `addOpenTypeFeaturesFromString` as Just suggested, which wraps a `features` string in a StringIO. This optionally takes a further `filename` argument, used for displaying the name of the feature "file" when printing error messages, and also for resolving any relative include statements. If the filename is None, it will default to the string `<features>` (unlikely to be confused with a real file name); in that case, the root of the relative includes becomes the current working directory (since `os.path.dirname("<features>")` returns an empty string "").

Comments would be much appreciated!
Thanks.

**Comment by justvanrossum** [comment]
I haven't tested it, but it looks great to me. It's clear, flexible and easy to use.

**Comment by brawer** [comment]
Looks good to me, too.

**Comment by anthrotype** [comment]
Thanks! Feel free to reopen this issue or a new one if you think we need further changes.
