### ISSUE TITLE
[feaLib] inline lookup is not exported

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#461]
Consider the following feature file:

```
@FIGURES_DEFAULT = [zero one two three four five six seven eight nine];
@FIGURES_INFERIOR = [zero.subs one.subs two.subs three.subs four.subs five.subs six.subs seven.subs eight.subs nine.subs];

feature subs {
    lookup INFERIOR {
        sub @FIGURES_DEFAULT by @FIGURES_INFERIOR;
    } INFERIOR;
} subs;

feature sinf {
    lookup INFERIOR;
} sinf;
```

I get the error: `Unknown lookup INFERIOR` which seems to suggest that feaLib doesn't export lookups defined inside a feature for use elsewhere.

cc @brawer

**Comment by anthrotype** [comment]
I believe that's not an issue. If a lookup is meant to be used by more than one feature, then you should move it outside of the scope of features and make it stand-alone.
If makeotf does it otherwise, maybe it's wrong...

**Comment by anthrotype** [comment]
well, if makeotf does that way, I guess we should also do it that way (despite for me it's counterintuitive, as it would make things clearer to define that as standalone lookup)

**Comment by adrientetar** [comment]
Such syntax is used in feature files of Adobe's open-source fonts, e.g.[here](https://github.com/adobe-fonts/source-sans-pro/blob/c784a39/Roman/family.fea#L636).

**Comment by miguelsousa** [comment]
@anthrotype writing a feature as
```
feature abcd {
    lookup ABCD {
        sub a by a.alt;
    } ABCD;
} abcd;
```
is not less valid than writing it as
```
feature abcd {
    sub a by a.alt;
} abcd;
```
The former actually makes more explicit what goes on behind the scenes.

**Comment by anthrotype** [comment]
of course. I meant for clarity's sake, if that `lookup ABCD` is also used elsewhere, then it would be better defined outside the scope of `feature abcd`.

**Comment by anthrotype** [comment]
I mean

```
lookup ABCD {
    sub a by a.alt;
} ABCD;

feature abcd {
   lookup ABCD;
} abcd;

feature efgh {
   lookup ABCD;
} efgh;
```

instead of

```
feature abcd {
   	lookup ABCD {
        sub a by a.alt;
    } ABCD;
} abcd;

feature efgh {
   lookup ABCD;
} efgh;
```

**Comment by anthrotype** [comment]
anyway, mine is simply a stylistic concern. The issue as reported by @adrientetar remains that feaLib should handle these named lookups defined within the scope of a feature block the same way that makeotf does (i.e. "scope-less").

**Comment by brawer** [comment]
Agree. Working on a fix.

**Comment by brawer** [comment]
By the way, the spec is silent about scoping; see https://github.com/adobe-type-tools/afdko/issues/98.

**Comment by twardoch** [comment]
Up until AFDKO 1.5 or so, it was ONLY possible to define a lookup INSIDE a feature block, and then refer to such lookups in subsequent features. So from the very beginning, the lookup keyword had only the global scope. 

I proposed that AFDKO adds the ability to define lookups outside of feature blocks because that method gave better clarity over the order of lookups, which is relevant. The original method obscured it a bit. 

But in both methods (which can be mixed), the scope is global, and should be treated as such. 

There are TONS of existing sources which have definitions like this: 

feature ss01 { 
  lookup ss01 { 
    sub a by b;
  } ss01; 
} ss01; 

feature salt { 
  lookup ss01; 
} salt; 

and feaLib should treat them the same as:

lookup ss01 { 
    sub a by b;
} ss01; 

feature ss01 { 
  lookup ss01;
} ss01; 

feature salt { 
  lookup ss01; 
} salt; 

Note that only the first example is valid FEA from AFDKO 1.0 oneards. The 2nd example is only valid in AFDKO 1.6+ or so, but there are many many source fonts that only use the 1st type of syntax.

**Comment by brawer** [comment]
Yes, I think that's what's implemented now.

**Comment by twardoch** [comment]
Thanks, I just wanted to clarify that the global scope of lookup names is by design, not by accident. I believe that class or markclass names are also global in scope. 

I do agree though that the FEA spec could be more clear about this.
