### ISSUE TITLE
[feaLib] Parser should understand contextual chained SinglePos rules

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#481]
feaLib rejects the following feature file. However, makeotf v2.0.90 accepts this input, and interprets it as a chain rule for a SinglePos.
```
feature kern {
    pos [F T] [period]' -25;
} kern;
```

Althought the OpenType Feature File specification does not seem to give an example for this construct, its semantics is obvious. So feaLib should recognize it and produce the same output as makeotf.

**Comment by twardoch** [comment]
Yes, makeOTF has a number of built-in optimizations that try to simplify certain constructs and express them in a "simpler" lookupType. This is sometimes a bit of a double-edged sword because the makeOTF feature parsing has an implicit "current lookup type" context. So when a feature definition contains rules immediately, without an explicit lookup definition, makeOTF "somehow" determines what the current lookup type should be. If the processor finds a foreign rule within the same flow, it protests. 

This is not obvious behavior because these two snippets should probably yield different results: 

feature kern {
    pos [Y V] A -30;
    pos [F T] [period]' -25;
} kern;

feature kern {
    pos T [period comma]' A -45; 
    pos [F T] [period]' -25;
} kern;

Or not?

**Comment by twardoch** [comment]
(Or maybe I'm mistaken and thissimplification does not happen.)

**Comment by brawer** [comment]
> makeOTF has a number of built-in optimizations that try to simplify certain constructs
> and express them in a "simpler" lookupType

Do you have examples where this happens?

**Comment by brawer** [comment]
I’m opening another issue for the parser bug: https://github.com/behdad/fonttools/issues/485, so that we can continue talking about changing lookup types here. Essentially, this would be an optimization. makeotf doesn’t seem to do it, but perhaps it should; eg., in the initial example on this bug, the result would be 12 bytes smaller and (perhaps more important) one less lookup, so the layout engine would have to hop around less between tables. Optimization will be an interesting topic, but it’s independent of fixing the parser. For now, I’d like to make it correct first.

**Comment by brawer** [comment]
Moved the optimization proposal to https://github.com/behdad/fonttools/issues/487
