### ISSUE TITLE
Use Zopfli compression for WOFF files

### ISSUE THREAD

**Issue by RoelN** [behdad/fonttools#491]
Creating a WOFF1 font with ttx/fonttools results in a larger file than when you create a TTF file and then compress it with tools like [sfnt2woff-zopfli](https://github.com/bramstein/sfnt2woff-zopfli) or [ttf2woff](http://wizard.ae.krakow.pl/~jb/ttf2woff/), which use Zopfli compression. It would be nice to directly output an optimal compressed font.

**Comment by anthrotype** [comment]
That's a good idea! I'll find a good zopfli Python binding and use that instead of zlib when the user has it installed. Would that be ok?

**Comment by RoelN** [comment]
Sounds perect! :)

**Comment by twardoch** [comment]
Keep in mind that Zopfli is about 20-40x slower than zlib, and gives 3-8% better compression. Zopfli, just like Brotli that's used in WOFF2, is really slow when compressing. Depending on the particular usecase, I'd prefer to keep the ability (option) to use zlib (for example when fontTools is used for mass processing or subsetting).

**Comment by anthrotype** [comment]
Hmm I see. I'll test this and see what comes up.
Would you prefer to have an option lik like `--with-zopfli` and keep zlib as the default, or instead a `--with-zlib` option use zopfli as default -- provided of course it's installed (otherwise fall back to zlib)?

**Comment by LettError** [comment]
I would prefer the default to be fast and independent of external packages. 
FWIW, in the AFDKO the extra "release" compression is optional as well. 

Erik

**Comment by anthrotype** [comment]
ok then, we shall keep it optional.

**Comment by twardoch** [comment]
Given that the majority of mass-scale uses of fontTools still probably is on raw SFNT, and WOFF[2] operations are still relatively rare, I’d say Zopfli is OK as default, with a way to explicitly ask for zlib. "Good but slow" WOFF creation will probably be more useful to most people while "fast but less good" is limited to more specialized cases.

**Comment by twardoch** [comment]
On second thoughts, Erik makes a good point.

**Comment by anthrotype** [comment]
So, I reviewed the existing Python bindings for Zopfli. There are two alternative packages, both available on PyPI. Neither is compatible with Python 3... :(

- [zopfli](https://github.com/wnyc/py-zopfli): simple wrapper around zopfli's `ZlibCompress` and `GzipCompress` methods.
    source: 

- [pyzopfli](https://github.com/Scondo/py-zopfli): this seems more promising; it originated as a fork of the above, and provides the same interface as the standard zlib module so it can be used as a drop-in replacement.

Both were last edited around 3 years ago and never updated since. They embed copies of the Zopfli C source files, checked out at the time the bindings were originally developed. On the other hand, the google/zopfli upstream repository has commits from few days ago.
 
Implementing support for Zopfli in fonttools would require:

- making the extension module compatible with Python 3
- updating them to use the the latest zopfli C source files (preferably as git submodule).
- deciding how to pass the command line option down to the SFNTWriter instance, so it uses zopfli instead of zlib.

Finally, I run some tests compressing WOFFs in fonttools with these zopfli extensions, and indeed, like Adam said, it is _extremely_ slow, and the gain is relatively small.

**Comment by anthrotype** [comment]
Oh, I forgot to mention: neither of the existing zopfli extension modules seems to compile on Windows.

**Comment by anthrotype** [comment]
I made the zopfli bindings work with both Python 2 and 3, as well as on Windows.

I make it build from the latest C sources from google/zopfli, pulled in as git submodule.
I also submitted a [pull request](https://github.com/wnyc/py-zopfli/pull/9) to the original maintainer.

My fork lives at https://github.com/anthrotype/py-zopfli.
You can install the package with pip:

```
pip install -v git+https://github.com/anthrotype/py-zopfli#egg=zopfli
```

And you use it like that:
```python
>>> from zopfli.zlib import compress
>>> from zlib import decompress
>>> decompress(compress(b"hello"))
b'hello'
```

Tomorrow I'll add the option to use it when compressing WOFF 1.0 with fonttools.

**Comment by RoelN** [comment]
Fantastic work, @anthrotype! Thanks for picking this up, and doing this so quickly. Much appreciated!

**Comment by RoelN** [comment]
Zopfli sure slows things down: converting a font takes about 80 seconds with ttx, while [ttf2woff](http://wizard.ae.krakow.pl/~jb/ttf2woff/) takes about 15 seconds and results in an even smaller file (69kB as opposed to ttx' 76kB).

Any thoughts on why this is, or what I can do to speed this up?

**Comment by anthrotype** [comment]
ttx compile the TTFont instance with "reorderTables=True" by default, and that makes the process twice as slow as it would normally be, since to reorder the tables (according to the recommended spec order) it has to decompress and recompress again. We should add an option so the user can skip that (by setting "reorderTables=None" when saving a TTFont), like the pyftsubset allows to do.

The size difference is strange. Could you post a link to the font if it's a publicly available one (or maybe send it privately to my name dot surname at daltonmaag dot com)?

Thanks

**Comment by anthrotype** [comment]
Just checked the ttf2woff source and it appears it runs some optimizations to loca, name and hmtx table so it drops the DSIG table after it becomes invalidated. That might explain the size differences. Btw, also pyftsubset I think drops DSIG by default, among other things.

**Comment by LettError** [comment]
Any kind of compression takes time, no?

Erik

**Comment by behdad** [comment]
> ttx compile the TTFont instance with "reorderTables=True" by default, and that makes the process twice as slow as it would normally be, since to reorder the tables (according to the recommended spec order) it has to decompress and recompress again.

We definitely should not compress the first round!  Better yet, how about keeping compiled tables in memory and writing them out in order?  Definitely need to clean up this part of the code a bit.

**Comment by behdad** [comment]
> Creating a WOFF1 font with ttx/fonttools results in a larger file than when you create a TTF file and then compress it with tools like sfnt2woff-zopfli or ttf2woff, which use Zopfli compression. It would be nice to directly output an optimal compressed font.

Can you try with pyftsubset?

**Comment by RoelN** [comment]
I've run the tests again, this time on my OSX machine, with everything up to date. Sizes, from small to large:

- 69696 bytes (`sfnt2woff-zopfli NTBixa-Color.ttf`)
- 69772 bytes (`ttx --flavor woff --with-zopfli NTBixa-Color.ttx`)
- 69780 bytes (`pyftsubset --flavor=woff --with-zopfli --no-subset-tables+='SVG ' --drop-tables-='SVG ' NTBixa-Color.ttf '*'`)
- 76532 bytes (`ttf2woff NTBixa-Color.ttf NTBixa-Color.woff`)

Input font is something I'm working on. It's not public yet but I don't mind sending over a copy through mail. The only thing special about this test font is that it contains an 'SVG ' table.

It's weird to see ttf2woff perform the worst here. I'll look at the original setup (a linux shared hosting webserver) and see if I made a mistake or wasn't working with up-to-date tools. Also, on my Macbook all tools now take a maximum of 5 seconds to finish the while process.

**Comment by anthrotype** [comment]
what I'm actually surprised is that the output from ttx looks smaller than the one from pyftsubset. The latter applies various optimizations for webfont use, unlike ttx which simply compiles the XML data you feed it.

**Comment by RoelN** [comment]
@anthrotype I've sent you the font I'm working with per mail, maybe that'll help with figuring out why this is?
