### ISSUE TITLE
[feaLib] Glyph classes should be lists, not sets

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#504]
The following is currently rejected by feaLib. The root cause is that glyph classes are currently represented as sets; should be lists instead.

Input:
```
feature test {
    sub [a b c d] by [T E S T];
} test;
```

Expected output:
```
        <SingleSubst index="0">
          <Substitution in="a" out="T"/>
          <Substitution in="b" out="E"/>
          <Substitution in="c" out="S"/>
          <Substitution in="d" out="T"/>
        </SingleSubst>
```

Observed:
```
bug.fea:2:5: Expected a glyph class with 4 elements after "by", but found a glyph class with 3 elements
```

**Comment by marekjez86** [comment]
The most recent pipeline pull that I built and ran fixes the above issue. Thanks for fixing it.

**Comment by twardoch** [comment]
Yes, that's a biggie. In an ideal world, there should be classes that are lists and there should be classes that are sets. For UFO-style group kerning or contextual GSUB substitutions, classes should be sets, for "class by class"
GSUB substitution shorthand, they should be lists. But since there is no way to cleanly tell them apart, classes should be lists on the level of feaLib.

**Comment by anthrotype** [comment]
👍
