### ISSUE TITLE
Problem with integration of zopfli

### ISSUE THREAD

**Issue by Arno-Enslin** [behdad/fonttools#610]
@ anthrotype

Please have a look on [this issue.](https://github.com/google/zopfli/issues/115)

**Comment by anthrotype** [comment]
The issue was that Visual Studio's `<stdlib.h>` header contains a non-standard macro definition which conflicts with the function named `min` in zopfli's `squeeze.c` file.

The fix is to pass a compiler flag `/Za` that tells Visual Studio to stop using MS-specific language extensions which are not ANSI C compatible, like the `min` macro above.

I've pushed a commit to py-zopfli that fixes this. Please let me know if it works now.

https://github.com/anthrotype/py-zopfli/releases/tag/0.0.7
 
Remember to use `--recursive` flag when cloning the py-zopfli repository:
```
$ git clone --recursive https://github.com/anthrotype/py-zopfli
```

This ensures that the included submodule with the `zopfli` C sources is cloned as well.

In case you have already cloned py-zopfli, you can update the submodule by doing:

```bash
$ git submodule update --init
```

BTW, the next time you should open the issue on the py-zopfli repository, instead of fonttools.

And thanks a lot for spotting this!

**Comment by Arno-Enslin** [comment]
> BTW, the next time you should open the issue on the py-zopfli repository

I had not seen en issue section in the repository [https://github.com/anthrotype/py-zopfli]("https://github.com/anthrotype/py-zopfli").

**Comment by anthrotype** [comment]
you are right. Now there is :)

**Comment by Arno-Enslin** [comment]
> Remember to use --recursive flag when cloning the py-zopfli repository:
> 
> $ git clone --recursive https://github.com/anthrotype/py-zopfli

Sorry, but I don't understand that. Git clone? This is obviously a command. Where is this explained?

In the past I simply followed the link to the submodule, copied it and merged it into the py-zopfli-master. Manually.

I opften loose the overview in all the masters, trees, commits. Not only because of my English.

**Comment by moyogo** [comment]
@Arno-Enslin GitHub has some guide on how to fork and clone a repository, as well as keeping it in sync, with the command line: https://help.github.com/articles/fork-a-repo/
