### ISSUE TITLE
Dump contour values relative to each other instead of (0, 0)

### ISSUE THREAD

**Issue by RoelN** [behdad/fonttools#661]
In [the spec](https://www.microsoft.com/typography/OTSPEC/glyf.htm) I read about coordinates:

`First coordinates relative to (0,0); others are relative to previous point.`

Yet the coordinates dumped with ttx/FontTools all seem to be relative to (0, 0). Is there any way to dump/compile them relative to the previous point?

**Comment by behdad** [comment]
There isn't.  The compiler concerts them to absolute.  We consider that a bye encoding detail. Why do you need that?

**Comment by RoelN** [comment]
When coordinates are absolute you can't move a point farther than 32,767. Currently `<pt x="-16383" y="16383" on="1"/>` works, but `<pt x="-16384" y="16384" on="1"/>` crashes ttx/FontTools with the message `OverflowError: signed short integer is greater than maximum`. This is half the value of an unsigned int, so I didn't expect that.

With relative values I can work around this making steps of the maximum value so I end up at my ridiculous large value.

I am experimenting so I understand you probably won't need this for production stuff.

**Comment by behdad** [comment]
You are misinterpreting the error.  What we expose to user doesn't limit anything.  You get the error because the **relative** step from -16384 to +16384 does not fit into a SHORT. You are free to take as many large steps as you want as long as the difference between consecutive ones does not exceed the SHORT range (-32768..+32767)

**Comment by RoelN** [comment]
Ah yes, check. Thanks for the explanation!
