### ISSUE TITLE
the head table 'created'/'modified' counts from unix epoch instead of 1904

### ISSUE THREAD

**Issue by Pomax** [behdad/fonttools#99]
As per http://www.microsoft.com/typography/otspec/head.htm, the dates for `created` and `modified` in the `head` table are specified as the number of seconds since 12:00 midnight, January 1, 1904. However, TTX seems to be counting from Unix epoch (Thu Jan 01 00:00:00 1970) instead, leading to incorrect created/modified dates.

**Comment by behdad** [comment]
Ok, I fixed the exception type.

I like ignoring the top four bytes.  That said, your numbers don't look right to me.

**Comment by behdad** [comment]
Err, broken commits.  Fixing.

**Comment by olivierberten** [comment]
What do you mean "don't look right " ?

By the way, the version field of the font says "Macromedia Fontographer 4.1 9/17/95" which fits with the 4 bytes date ;-)

**Comment by behdad** [comment]
All fixed with: https://github.com/behdad/fonttools/commit/b056318ca9ddc17855fe1c8191d61ff38f0f4f7e

As a result, removed the exception handling code.  Which makes me much happier.

By "don't look right" I meant, the lower four bytes of 18446181438100104661 and 9083198122034488789 and indeed the same, but they are 811361749, not 2894206549.  Right?

**Comment by olivierberten** [comment]
Oops... I had converted them to unix epoch...

**Comment by behdad** [comment]
Got it.  So, everything looks good now?

**Comment by olivierberten** [comment]
It does indeed.

**Comment by olivierberten** [comment]
#206
